version: 2.1
jobs:
  snx:
   docker:
      - image: nexgang/ubuntu:latest
   steps:
      - run:
          command: |
           git config --global user.name "ImSpiDy"
           git config --global user.email "SpiDy2713@gmail.com"
           git config --global color.ui false
workflows:
  version: 2.1
  cooking:
    jobs:
      - echo "Skip"
